platform: linux
image_resource:
  type: docker-image
  source:
    repository: mhart/alpine-node
    tag: latest
inputs:
- name: cg-docs-source
outputs:
- name: cg-docs-compiled
run:
  dir: cg-docs-source
  path: ci/build.sh
