platform: linux
image_resource:
  type: docker-image
  source:
    repository: 18fgsa/cg-docs
inputs:
- name: cg-docs-source
outputs:
- name: cg-docs-compiled
run:
  dir: cg-docs-source
  path: ci/build.sh
